collections:
  columns
    order: 
      - columns/inequality and inefficiency.md

# port: 4000
# markdown:  kramdown
plugins: [ jekyll-feed, jekyll-seo-tag ]

permalink: /:categories/:title/



title :       "Abrham Bas"
description : "This is my personal site where I post all about my life, just think of it as my commonplace"
author :      "Abr Bas"
url :         https://abrdgr8.netlify.app/


feed:
  path: /blog/feed.atom


## Disqus comments
disqus_shortname: # Disqus will not be used unless this is set
disqus_developer: 0 # 1 | 0

### Isso comments
use_isso: "no" # "no" | "yes"
  
kramdown:
  auto_ids: true

### Jekyll Admin: uncomment the last two lines of this paragraph to enable Jekyll Admin.
### (but you will loose auto regeneration after code changes with a text editor then)
# plugins:
#  - jekyll-admin